# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: UNITADE.md

  # A short description of the repository that will show up on GitHub
  description: "A plugin for note-taking app Obsidian‚Ñ¢ which allows you to treat any file extension as markdown note-file"

  # A URL with more information about the repository
  homepage: ""

  # A comma-separated list of topics to set on the repository
  topics: plugin, markdown, files, typescript, file-format, obsidian, obsidian-plugin

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: true

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

  # Either `true` to enable automatic deletion of branches on merge, or `false` to disable
  delete_branch_on_merge: true

  # Either `true` to enable automated security fixes, or `false` to disable
  # automated security fixes.
  enable_automated_security_fixes: true

  # Either `true` to enable vulnerability alerts, or `false` to disable
  # vulnerability alerts.
  enable_vulnerability_alerts: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: announcement üì£
    color: "#0075ca"
  - name: api-review/approved ‚úÖ
    color: "#d73a4a"
  - name: api-review/declined ‚ùå
    color: "#d73a4a"
  - name: api-review/requested üó≥
    color: "#d73a4a"
  - name: api-review/reviewed
    color: "#d73a4a"
  - name: arch/arm
    color: "#cfd3d7"
  - name: arch/arm64
    color: "#cfd3d7"
  - name: arch/x64
    color: "#cfd3d7"
  - name: arch/x86
    color: "#cfd3d7"
  - name: backport/approved ‚úÖ
    color: "#d876e3"
  - name: backport/declined ‚ùå
    color: "#d876e3"
  - name: backport/requested üó≥
    color: "#d876e3"
  - name: backport
    color: "#b9927c"
    description: "Issue or pull request related to backport"
  - name: blocked/need-info ‚ùå
    color: "#b60205"
    description: "Cannot proceed without more information"
  - name: blocked/need-repro
    color: "#b60205"
    description: "Needs a test case to reproduce the bug"
  - name: blocked/upstream ‚ùå
    color: "#b60205"
    description: "Blocked on upstream"
  - name: blocks-release
    color: "#7057ff"
    description: "Releases shouldn't go out without this fix"
  - name: bug
    color: "#e4e669"
  - name: crash üí•
    color: "#006b75"
  - name: dependencies
    color: "#a3452c"
    description: "Pull requests that update a dependency file"
  - name: deprecation-review/complete ‚úÖ
    color: "#e22801"
  - name: deprecation-review/requested üìù
    color: "#e22801"
  - name: discussion
    color: "#f463e9"
  - name: not-merging
    color: "#a21855"
  - name: documentation üìì
    color: "#a2eeef"
  - name: duplicate
    color: "#ffffff"
  - name: enhancement ‚ú®
    color: "#008672"
  - name: has-repro-comment
    color: "#71a111"
  - name: has-repro-gist
    color: "#71a111"
  - name: has-repro-repo
    color: "#71a111"
  - name: invalid
    color: "#c3d22b"
  - name: machine-dependent
    color: "#704c92"
  - name: machine
    color: "#704c92"
  - name: main
    color: "#659c0b"
  - name: security/memory
    color: "#b160a1"
  - name: security/data
    color: "#b160a1"
  - name: security/leak
    color: "#b160a1"
  - name: no-backport
    color: "#05263e"
  - name: performance üèÅ
    color: "#f7df40"
  - name: platform/all
    color: "#b79ccd"
  - name: platform/linux
    color: "#b79ccd"
  - name: platform/macos
    color: "#b79ccd"
  - name: platform/windows
    color: "#b79ccd"
  - name: release
    color: "#73a854"
  - name: release-notes/highlight
    color: "#c88887"
  - name: release-notes/mentioning
    color: "#c88887"
  - name: release-notes/common
    color: "#c88887"
  - name: security üîí
    color: "#4287b9"
  - name: semver/major
    color: "#465341"
  - name: semver/minor
    color: "#465341"
  - name: semver/none
    color: "#465341"
  - name: semver/patch
    color: "#465341"
  - name: stale
    color: "#63b8ba"
  - name: status/confirmed
    color: "#c4c880"
  - name: status/reviewed
    color: "#c4c880"
  - name: status/declined
    color: "#c4c880"
  - name: status/staling
    color: "#c4c880"
  - name: unsupported-version
    color: "#10a9e7"
  - name: WOA
    color: "#94cbc1"
  - name: WIP
    color: "#b89022"
  - name: WONTFIX
    color: "#9f24fa"
  - name: question
    color: "#5bb222"
  - name: repository
    color: "#1bd867"
  - name: repository/javascripts
    color: "#1bd867"
  - name: repository/pages
    color: "#1bd867"
  - name: repository/other
    color: "#1bd867"
  - name: status/considered
    color: "#e2d8e2"
    description:
  - name: status/planned
    color: "#c2f75a"
    description:
  - name: status/ignored
    color: "#4386db"
    description:
  - name: status/denied
    color: "#4386db"
    description:
  - name: status/accepted
    color: "#154e5e"
    description:
  - name: status/fixed
    color: "#154e5e"
    description:
  - name: status/implemented
    color: "#c603ad"
    description:
  - name: priority/extreme
    color: "#ff5733"
    description:
  - name: priority/high
    color: "#ff8333"
    description:
  - name: priority/medium
    color: "#d4ac0d"
    description:
  - name: priority/low
    color: "#13ff00"
    description:
  #- name:
  #  color: ''
  #  description:

# Milestones: define milestones for Issues and Pull Requests
milestones:
  - title: Public release of project
    description: "A preparations and milestone, including everything to prepare for one final release to publish project as ready-to-use without any bugs, leaks, security problems and etc., doesn't mean that project won't be updated and etc."
    state: closed
  #- title: milestone-title
  #description: milestone-description
  # The state of the milestone. Either `open` or `closed`
  #state: open

# Collaborators: give specific users access to this repository.
# See https://docs.github.com/en/rest/reference/repos#add-a-repository-collaborator for available options
#collaborators:
# - username: bkeepers
#   permission: push
# - username: hubot
#   permission: pull

# Note: `permission` is only valid on organization-owned repositories.
# The permission to grant the collaborator. Can be one of:
# * `pull` - can pull, but not push to or administer this repository.
# * `push` - can pull and push, but not administer this repository.
# * `admin` - can pull, push and administer this repository.
# * `maintain` - Recommended for project managers who need to manage the repository without access to sensitive or destructive actions.
# * `triage` - Recommended for contributors who need to proactively manage issues and pull requests without write access.

# See https://docs.github.com/en/rest/reference/teams#add-or-update-team-repository-permissions for available options
teams:
  - name: core
    # The permission to grant the team. Can be one of:
    # * `pull` - can pull, but not push to or administer this repository.
    # * `push` - can pull and push, but not administer this repository.
    # * `admin` - can pull, push and administer this repository.
    # * `maintain` - Recommended for project managers who need to manage the repository without access to sensitive or destructive actions.
    # * `triage` - Recommended for contributors who need to proactively manage issues and pull requests without write access.
    permission: admin
  - name: docs
    permission: push

# Keep in mind, that protections need to be made by your own, app checks the requirements and parameters, but does not
# set up or create them just as with code analysis and other security settings.
branches:
  - name: main
    # https://docs.github.com/en/rest/reference/repos#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: true
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions:
          users: []
          teams: []
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: []
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Prevent merge commits from being pushed to matching branches
      required_linear_history: true
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        apps: []
        users: []
        teams: []
  - name: development
    # https://docs.github.com/en/rest/reference/repos#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 0
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: false
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: false
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions:
          users: []
          teams: []
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: []
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: false
      # Prevent merge commits from being pushed to matching branches
      required_linear_history: false
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        apps: []
        users: []
        teams: []
  - name: development-ref
    # https://docs.github.com/en/rest/reference/repos#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 0
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: true
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions:
          users: []
          teams: []
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: []
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: false
      # Prevent merge commits from being pushed to matching branches
      required_linear_history: true
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        apps: []
        users: []
        teams: []
